### ISSUE TITLE
Code needs to be synced/updated with latest merlin-agent?

### ISSUE THREAD

**Issue by symmetrisch** [Ne0nd0g/merlin-agent-dll#1]
I suppose the code is not "in sync" with latest *merlin-agent*? On latest Kali/Debian, I tried:

`git clone https://github.com/Ne0nd0g/merlin-agent-dll.git`
`cd merlin-agent-dll`
`go mod download github.com/Ne0nd0g/merlin-agent`
`go get github.com/Ne0nd0g/merlin-agent/agent@latest`
`go get github.com/Ne0nd0g/merlin-agent/clients/http@v1.2.0`
`make`

and received

`./main.go:68:3: cannot use URL (type string) as type []string in field value`

I "fixed" this by removing the following line in `main.go`

`URL:         URL,`

and adding the following code:

`if URL != "" {`
`	clientConfig.URL = strings.Split(strings.ReplaceAll(URL, " ", ""), ",")`
`}`

However, I am not sure if this is really complete or just "made the compiler happy". Output (dll) was working though.

**Comment by Ne0nd0g** [comment]
Yes, that is correct. I need to update this repository to use the latest `v1.2.0` Merlin packages. I'll work on updating that. 

The `go.mod` file constrains the imported package libraries to [github.com/Ne0nd0g/merlin-agent v1.0.0](https://github.com/Ne0nd0g/merlin-agent-dll/commit/7ebd1b99dcd7743c8dc2dc07edfa6b8ba4ba3319#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R4) and [github.com/Ne0nd0g/merlin v0.11.0-beta](https://github.com/Ne0nd0g/merlin-agent-dll/commit/7ebd1b99dcd7743c8dc2dc07edfa6b8ba4ba3319#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R7) for the current `master` branch. Try using `go mod download` in the repositories directory to ensure the intended package version are downloaded.

```text
rastley@ubuntu:/tmp$ git clone https://github.com/Ne0nd0g/merlin-agent-dll
Cloning into 'merlin-agent-dll'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 24 (delta 8), reused 24 (delta 8), pack-reused 0
Unpacking objects: 100% (24/24), 32.66 KiB | 3.27 MiB/s, done.
rastley@ubuntu:/tmp$ cd merlin-agent-dll/
rastley@ubuntu:/tmp/merlin-agent-dll$ go mod download
rastley@ubuntu:/tmp/merlin-agent-dll$ make
export GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ CGO_ENABLED=1; \
go build -ldflags '-s -w -X main.build=8b17d8559377825a091ce89b94a224c76e40c56f -X github.com/Ne0nd0g/merlin/pkg/agent.build=8b17d8559377825a091ce89b94a224c76e40c56f -X main.protocol=h2 -X main.url=https://127.0.0.1:443 -X main.host= -X main.psk=merlin -X main.proxy= -X main.killdate=0 -X main.maxretry=7 -X main.padding=4096 -X main.skew=0 -X "main.useragent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.85 Safari/537.36" -X main.sleep=30s -buildid=' -gcflags=all=-trimpath= -asmflags=all=-trimpath= -buildmode=c-archive -o bin/v"1.0.0"/8b17d8559377825a091ce89b94a224c76e40c56f/main.a main.go; \
cp merlin.c bin/v"1.0.0"/8b17d8559377825a091ce89b94a224c76e40c56f; \
x86_64-w64-mingw32-gcc -shared -pthread -o bin/v"1.0.0"/8b17d8559377825a091ce89b94a224c76e40c56f/merlin.dll bin/v"1.0.0"/8b17d8559377825a091ce89b94a224c76e40c56f/merlin.c bin/v"1.0.0"/8b17d8559377825a091ce89b94a224c76e40c56f/main.a -lwinmm -lntdll -lws2_32
rastley@ubuntu:/tmp/merlin-agent-dll$ 

```

**Comment by Ne0nd0g** [comment]
The `dev` branch was previously updated to `v1.1.0` and included the functionality you identified for parsing URLs [here](https://github.com/Ne0nd0g/merlin-agent-dll/commit/c9f4b8e627d7c09607339478121677f0158a4bde#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R76). However, I did forget to merge `dev` into `master`
