### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by breachlabs-org** [Ne0nd0g/merlin-agent-dll#4]
Hello, i am trying to use the DLL Agent in a current test and i'm unable to compile it.

Environment : Ubuntu 23.04
Error message:

```
go build -buildmode=c-archive main.go
```

```
# github.com/lucas-clemente/quic-go/internal/qtls
../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.31.1/internal/qtls/go120.go:5:13: 
```

```
cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
```

Thank you for your help!

**Comment by Ne0nd0g** [comment]
The error is showing that the code can't be compiled with go 1.20. You will need to use go 1.19 . I am aware of this and will be pushing an update in the next couple of weeks to resolve this. If you can't use go 1.19 right now, let me know and I'll develop a work around.

**Comment by Ne0nd0g** [comment]
Same issue and solution as https://github.com/Ne0nd0g/merlin-agent/issues/29
